feat: add support for aurelia 2 project detection
denofevil/AureliaStorm pull request #42
Opened 2023-05-22 14:31 UTC by CollinHerber

Sorry if there is things missing, bad, etc. This is my first ever intellij plugin and I also have not written any Java/Kotlin in 10+
 years.

This changes the following
* Removes the file name based detection for telling if aurelia is present
* Add dependency based detection. (aurelia-cli = v1 , aurelia = v2)
* Adds contribution documentation to satisfy https://github.com/denofevil/AureliaStorm/issues/41

Adds support for the following
* switch and case binding
* ref is considered a valid attribute

I have confirmed this working on an aurelia 1 and aurelia 2 project. If I'm not mistaken these are the correct dependencies to check for.

2023-05-29 20:44 UTC, CollinHerber commented
Can we get some traction on this?

2023-07-21 16:08 UTC, anstarovoyt requested changes

2023-07-21 16:11 UTC, anstarovoyt commented
sorry, I wrote a comment in May but looks like I didn't submit it as a part of review 🤦

2023-07-21 16:13 UTC, anstarovoyt commented on README.md
> -Either `aurelia-framework.js`, `aurelia-bootstrapper.js` or `aurelia-core.js` must be present in the project sources
also, we still need to keep old behaviour for very old projects.

2023-07-21 21:54 UTC, closed without merging